# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import numpy as np

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar

from  matplotlib.figure  import  Figure


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QVBoxLayout

class MplWidget(QWidget):
    def __init__(self, parent=None):
        QWidget.__init__(self,parent)
        self.canvas = FigureCanvas(Figure())
        self.toolbar = NavigationToolbar(self.canvas, self)
        self.layout = QVBoxLayout(self)
        self.layout.addWidget(self.canvas)
        self.layout.addWidget(self.toolbar)
        self.canvas.axes = self.canvas.figure.add_subplot(1,1,1)
        self.canvas.axes.clear()
        # self.canvas.axes.plot(np.linspace(1,10),list(map(lambda x:x**2, np.linspace(1,10))))
        self.canvas.axes.set_title('Captured MCP')
        self.canvas.draw()

    def update_figure(self, x_val, y_val):
        self.canvas.axes.clear()
        self.canvas.axes.plot(x_val, y_val)
        self.canvas.axes.set_title('Captured MCP')
        self.canvas.draw()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_3.setObjectName("label_3")
        # self.verticalLayout_2.addWidget(self.label_3)
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_2.addWidget(self.MplWidget)
        self.save_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_data_button.setObjectName("save_data_button")
        self.verticalLayout_2.addWidget(self.save_data_button)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.mcp_level_form = QtWidgets.QFormLayout()
        self.mcp_level_form.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mcp_level_form.setObjectName("mcp_level_form")
        self.vbias_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.vbias_box.setDecimals(3)
        self.vbias_box.setMinimum(15.0)
        self.vbias_box.setMaximum(26.5)
        self.vbias_box.setSingleStep(0.001)
        self.vbias_box.setProperty("value", 26.0)
        self.vbias_box.setObjectName("vbias_box")
        self.mcp_level_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.vbias_box)
        self.vreset_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.vreset_box.setDecimals(3)
        self.vreset_box.setMinimum(-26.5)
        self.vreset_box.setMaximum(-15.0)
        self.vreset_box.setSingleStep(0.01)
        self.vreset_box.setProperty("value", -26.0)
        self.vreset_box.setObjectName("vreset_box")
        self.mcp_level_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vreset_box)
        self.live_rails = QtWidgets.QCheckBox(self.centralwidget)
        self.live_rails.setObjectName("live_rails")
        self.mcp_level_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.live_rails)
        self.rail_settings_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.rail_settings_push_button.setObjectName("rail_settings_push_button")
        self.mcp_level_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rail_settings_push_button)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.mcp_level_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.mcp_level_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.mcp_level_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.mcp_level_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.ibias_box = QtWidgets.QSpinBox(self.centralwidget)
        self.ibias_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ibias_box.setWrapping(False)
        self.ibias_box.setFrame(True)
        self.ibias_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ibias_box.setProperty("showGroupSeparator", False)
        self.ibias_box.setMaximum(150)
        self.ibias_box.setProperty("value", 20)
        self.ibias_box.setObjectName("ibias_box")
        self.mcp_level_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ibias_box)
        self.ireset_box = QtWidgets.QSpinBox(self.centralwidget)
        self.ireset_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ireset_box.setMaximum(150)
        self.ireset_box.setProperty("value", 20)
        self.ireset_box.setObjectName("ireset_box")
        self.mcp_level_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ireset_box)
        self.verticalLayout_3.addLayout(self.mcp_level_form)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.mcp_sweep_form = QtWidgets.QFormLayout()
        self.mcp_sweep_form.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mcp_sweep_form.setObjectName("mcp_sweep_form")
        self.sweep_bias_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sweep_bias_min.setDecimals(3)
        self.sweep_bias_min.setMinimum(15.0)
        self.sweep_bias_min.setMaximum(26.4)
        self.sweep_bias_min.setSingleStep(0.001)
        self.sweep_bias_min.setObjectName("sweep_bias_min")
        self.mcp_sweep_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sweep_bias_min)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.mcp_sweep_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.sweep_bias_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sweep_bias_max.setDecimals(3)
        self.sweep_bias_max.setMinimum(15.1)
        self.sweep_bias_max.setMaximum(26.5)
        self.sweep_bias_max.setSingleStep(0.001)
        self.sweep_bias_max.setProperty("value", 26.5)
        self.sweep_bias_max.setObjectName("sweep_bias_max")
        self.mcp_sweep_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sweep_bias_max)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.mcp_sweep_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.sweep_bias_step = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sweep_bias_step.setDecimals(3)
        self.sweep_bias_step.setMinimum(0.001)
        self.sweep_bias_step.setMaximum(10.0)
        self.sweep_bias_step.setSingleStep(0.001)
        self.sweep_bias_step.setObjectName("sweep_bias_step")
        self.mcp_sweep_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sweep_bias_step)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.mcp_sweep_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.sweep_reset_step = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sweep_reset_step.setDecimals(3)
        self.sweep_reset_step.setMinimum(0.001)
        self.sweep_reset_step.setMaximum(10.0)
        self.sweep_reset_step.setSingleStep(0.001)
        self.sweep_reset_step.setProperty("value", 0.1)
        self.sweep_reset_step.setObjectName("sweep_reset_step")
        self.mcp_sweep_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sweep_reset_step)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.mcp_sweep_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.sweep_reset_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sweep_reset_max.setDecimals(3)
        self.sweep_reset_max.setMinimum(-26.4)
        self.sweep_reset_max.setMaximum(-15.0)
        self.sweep_reset_max.setSingleStep(0.001)
        self.sweep_reset_max.setObjectName("sweep_reset_max")
        self.mcp_sweep_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sweep_reset_max)
        self.sweep_reset_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sweep_reset_min.setDecimals(3)
        self.sweep_reset_min.setMinimum(-26.5)
        self.sweep_reset_min.setMaximum(-15.1)
        self.sweep_reset_min.setSingleStep(0.001)
        self.sweep_reset_min.setProperty("value", -26.5)
        self.sweep_reset_min.setObjectName("sweep_reset_min")
        self.mcp_sweep_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sweep_reset_min)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.mcp_sweep_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.mcp_sweep_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_18)
        self.verticalLayout_3.addLayout(self.mcp_sweep_form)
        self.sweep_button = QtWidgets.QPushButton(self.centralwidget)
        self.sweep_button.setObjectName("sweep_button")
        self.verticalLayout_3.addWidget(self.sweep_button)
        self.halt_button = QtWidgets.QPushButton(self.centralwidget)
        self.halt_button.setObjectName("halt_button")
        self.verticalLayout_3.addWidget(self.halt_button)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.measured_max = QtWidgets.QLineEdit(self.centralwidget)
        self.measured_max.setReadOnly(True)
        self.measured_max.setObjectName("measured_max")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.measured_max)
        self.measured_min = QtWidgets.QLineEdit(self.centralwidget)
        self.measured_min.setReadOnly(True)
        self.measured_min.setObjectName("measured_min")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.measured_min)
        self.live_measure = QtWidgets.QCheckBox(self.centralwidget)
        self.live_measure.setObjectName("live_measure")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.live_measure)
        self.measure_button = QtWidgets.QPushButton(self.centralwidget)
        self.measure_button.setObjectName("measure_button")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.measure_button)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.operation_label = QtWidgets.QLabel(self.centralwidget)
        self.operation_label.setObjectName("operation_label")
        self.horizontalLayout_2.addWidget(self.operation_label)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfiguration = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Waveform_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Waveform_Data.setObjectName("actionSave_Waveform_Data")
        self.actionSpecify_GPIB_Addresses = QtWidgets.QAction(MainWindow)
        self.actionSpecify_GPIB_Addresses.setObjectName("actionSpecify_GPIB_Addresses")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave_Waveform_Data)
        self.menuFile.addAction(self.actionExit)
        self.menuConfiguration.addAction(self.actionSpecify_GPIB_Addresses)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label_3.setText(_translate("MainWindow", "Waveform Capture"))
        self.save_data_button.setText(_translate("MainWindow", "Save Data"))
        self.label_5.setText(_translate("MainWindow", "MCP Level Control"))
        self.live_rails.setText(_translate("MainWindow", "Live"))
        self.rail_settings_push_button.setText(_translate("MainWindow", "Update"))
        self.label_6.setText(_translate("MainWindow", "VBIAS (V)"))
        self.label_7.setText(_translate("MainWindow", "VRESET (V)"))
        self.label_8.setText(_translate("MainWindow", "IBAIS (mA)"))
        self.label_9.setText(_translate("MainWindow", "IRESET (mA)"))
        self.label_4.setText(_translate("MainWindow", "MCP Level Sweep Control"))
        self.label_13.setText(_translate("MainWindow", "VBIAS MIN (V)"))
        self.label_14.setText(_translate("MainWindow", "VBIAS MAX (V)"))
        self.label_15.setText(_translate("MainWindow", "VBIAS STEP (V)"))
        self.label_16.setText(_translate("MainWindow", "VRESET STEP (V)"))
        self.label_17.setText(_translate("MainWindow", "VRESET MIN (V)"))
        self.label_18.setText(_translate("MainWindow", "VRESET MAX (V)"))
        self.sweep_button.setText(_translate("MainWindow", "Sweep"))
        self.halt_button.setText(_translate("MainWindow", "Halt"))
        self.label_10.setText(_translate("MainWindow", "Measurement"))
        self.live_measure.setText(_translate("MainWindow", "Live"))
        self.measure_button.setText(_translate("MainWindow", "Update"))
        self.label_11.setText(_translate("MainWindow", "MAX (V)"))
        self.label_12.setText(_translate("MainWindow", "MIN (V)"))
        self.label_2.setText(_translate("MainWindow", "Status"))
        self.operation_label.setText(_translate("MainWindow", "No Op"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_Waveform_Data.setText(_translate("MainWindow", "Save Waveform Data"))
        self.actionSave_Waveform_Data.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSpecify_GPIB_Addresses.setText(_translate("MainWindow", "Specify GPIB Addresses"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Shift+X"))
